export const PROTECTED_ROUTES = {
    WORKSPACE: "/workspace/:workspaceId",
    TASKS: "/workspace/:workspaceId/tasks",
    MEMBERS: "/workspace/:workspaceId/members",
    SETTINGS: "/workspace/:workspaceId/settings",
    PROJECT_DETAILS: "/workspace/:workspaceId/project/:projectId",
    ORGANIZATION_DASHBOARD: "/organization/dashboard",
    ORGANIZATION_HIRE_AND_BOARD: "/organization/hire-and-board",
    ORGANIZATION_TIMESHEETS: "/organization/timesheets",
    ORGANIZATION_TIMESHEET_DETAIL: "/organization/timesheets/:timesheetId",
    ORGANIZATION_MY_INVOICES: "/organization/invoices/my-invoices",
    ORGANIZATION_MY_INVOICE_DETAIL: "/organization/invoices/my-invoices/:invoiceId",
    ORGANIZATION_GENERAL_INVOICES: "/organization/invoices/general-invoices",
    ORGANIZATION_GENERAL_INVOICE_DETAIL: "/organization/invoices/general-invoices/:invoiceId",
    ORGANIZATION_SYSTEM_SETUP_DOCUMENTS: "/organization/system-setup/documents",
    ORGANIZATION_SYSTEM_SETUP_DOCUMENT_EDIT: "/organization/system-setup/documents/edit",
    ORGANIZATION_SYSTEM_SETUP_EARNING_AND_DEDUCTION: "/organization/system-setup/earning-and-deduction",
    ORGANIZATION_SYSTEM_SETUP_EARNING_AND_DEDUCTION_EDIT: "/organization/system-setup/earning-and-deduction/edit",
    ORGANIZATION_SYSTEM_SETUP_MANAGE_ADMIN: "/organization/system-setup/manage-admin",
    ORGANIZATION_SYSTEM_SETUP_MANAGE_ADMIN_ADD: "/organization/system-setup/manage-admin/add",
    ORGANIZATION_CONTRACTS: "/organization/contracts",
    ORGANIZATION_CONTRACT_DETAIL: "/organization/contracts/:contractId",
    ADMIN_DASHBOARD: "/admin/dashboard",
    ADMIN_ORGANIZATIONS: "/admin/organizations",
    ADMIN_USERS: "/admin/users",
    ADMIN_USER_EDIT: "/admin/users/edit",
    ADMIN_CONTRACT: "/admin/contract",
    ADMIN_CONTRACT_DETAIL: "/admin/contract/:contractId",
    ADMIN_SIGNUP_REQUEST: "/admin/signup-request",
};
export const BASE_ROUTE = {
    INVITE_URL: "/invite/workspace/:inviteCode/join",
    LOGIN: "/",
    SIGN_UP: "/sign-up",
    FORGOT_PASSWORD: "/forgot-password",
    OTP: "/otp",
};
